# Welcome to Jekyll!
#

# Site settings
title: < / Nikesh Bajaj >
description: |
  PhD: 
  Signal Processing &  
  Machine Learning
owner: Nikesh Bajaj # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: n.bajaj@qmul.ac.uk
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nikeshbajaj.in" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/nikeshbajaj
  github: https://github.com/Nikeshbajaj
  linkedin-square: https://uk.linkedin.com/in/bajajnikesh
  facebook-official: http://facebook.com/nikeshbajaj.nikb
  google-plus-square: https://plus.google.com/u/0/+NikeshBajaj
  email: mailto:n.bajaj@qmul.ac.uk
  flickr: https://www.flickr.com/photos/nikeshbajaj
  instagram: https://www.instagram.com/nikeshbajaj/
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
